### ISSUE TITLE
one questions about the broadcast packets

### ISSUE THREAD

**Issue by ZhangYuanKai123** [AtharvSavarkar/ESPTouch-Python#1]
Hello, when I try to grab broadcast packets, I find that I can only grab a lot of 0 like the following figure. Is this normal ? Because I can't use this program to correctly configure the esp8266 network
![image](https://user-images.githubusercontent.com/96975259/173333629-62ab61e3-e810-42b5-a025-f0fccfec5f30.png)

**Comment by AtharvSavarkar** [comment]
Yes it is totally fine to receive zeros until you get any valid UDP packet from the chip
